services:
  openhands:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
      args:
        # Vite build-time vars (replace with your domain + Supabase values)
        VITE_BACKEND_BASE_URL: ${DOMAIN:?set in environment}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL:?set in environment}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY:?set in environment}
        # Cache-bust arg for frontend builder layer
        FRONTEND_REV: ${FRONTEND_REV:-dev}
    image: openhands:prod
    container_name: openhands-app
    # Bind to loopback only; Nginx will proxy from the public internet
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    environment:
      # Use prebuilt runtime image to skip local runtime builds (faster + robust)
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:-ghcr.io/all-hands-ai/runtime:oh_v0.54.0_vq4hl0089c5gti17_gpa9v1n2cj3x0ufg}

      # Select runtime: docker|remote|local|kubernetes|e2b (third_party)
      - RUNTIME=${RUNTIME:-e2b}
      # Ensure third-party runtime deps (e2b, etc.) are installed when using e.g. RUNTIME=e2b
      - INSTALL_THIRD_PARTY_RUNTIMES=true
      # E2B runtime API key (required if RUNTIME=e2b)
      - E2B_API_KEY=${E2B_API_KEY:-}
      # Workspace mount to the sandbox runtime (replaces WORKSPACE_* envs)
      - SANDBOX_VOLUMES=${SANDBOX_VOLUMES:-$PWD/workspace:/workspace:rw}

      # Public base URL (final public URL to render links)
      - PUBLIC_BASE_URL=https://${DOMAIN:?set in environment}
      # Supabase backend verification + per-user stores + auth
      - OPENHANDS_CONFIG_CLS=openhands.server.config.supabase_server_config.SupabaseServerConfig
      - OPENHANDS_CONVERSATION_VALIDATOR_CLS=openhands.storage.conversation.supabase_conversation_validator.SupabaseConversationValidator
      - SUPABASE_URL=${SUPABASE_URL:?set in environment}
      # Storage
      - FILE_STORE=local
      - FILE_STORE_PATH=/.openhands
      # Optional: tighten WebSocket connection requirements
      # - SESSION_API_KEY=${SESSION_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands:/.openhands
